services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: varun
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "8008:8080"
    networks:
      -db
    restart: unless-stopped

networks:
  db:
    driver: bridge

  volumes:
    db:

